### ISSUE TITLE
[PE-D][Tester A] Inconsistent Diagram Used in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-3/tp#110] opened 2023-03-31 16:54 UTC
The Diagram used in the User Guide for Find Command is the one for the original Address Book 3 instead of the AIMS app, which can cause potential confusion for the readers.

![Documentation Visual not consistent with the Current App.png](https://raw.githubusercontent.com/Yufannnn/ped/main/files/b0044499-5ef2-46a8-bcd6-948845b814af.png)

The personal card doesn't have the additional attributes added.

I suppose this can be fixed by uploading  a new screenshot.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Yufannnn/ped#4

**Comment by rexcyrio** [comment] 2023-04-04 07:27
Closed as duplicate of #128

**Closed by rexcyrio** 2023-04-04 07:27 UTC
