### ISSUE TITLE
[PE-D][Tester B] Tag too long 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-3/tp#136] opened 2023-03-31 19:22 UTC
![image.png](https://raw.githubusercontent.com/homuntan02/ped/main/files/556a4a05-e1f8-4004-8af3-c77fa6b8cdec.png)

cant read end of tag once tag is too long making it hard to tell if the tags are different. in my example above, the tags end with different numbers but you cant see it here. might wanna consider max lenght for tag.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: homuntan02/ped#7

**Comment by rexcyrio** [comment] 2023-04-04 07:35
Closed as duplicate of #106

**Closed by rexcyrio** 2023-04-04 07:35 UTC
